/* quotes.js */
const quotesData = [
    { en: "This too shall pass.", ko: "이 또한 지나가리라." },
    { en: "The best way to predict the future is to create it.", ko: "미래를 예측하는 가장 좋은 방법은 미래를 만드는 것이다." },
    { en: "Believe you can and you're halfway there.", ko: "할 수 있다고 믿으면 이미 절반은 온 것이다." },
    { en: "Life is what happens when you're busy making other plans.", ko: "인생이란 다른 계획을 세우느라 바쁜 와중에 일어나는 일들이다." },
    { en: "You only live once, but if you do it right, once is enough.", ko: "인생은 한 번뿐이지만, 제대로 산다면 한 번으로 충분하다." },
    { en: "Happiness depends upon ourselves.", ko: "행복은 우리 자신에게 달려있다." },
    { en: "Turn your wounds into wisdom.", ko: "상처를 지혜로 바꾸라." },
    { en: "Don't count the days, make the days count.", ko: "날짜를 세지 말고, 하루하루를 의미 있게 만들어라." },
    { en: "The journey of a thousand miles begins with one step.", ko: "천 리 길도 한 걸음부터." },
    { en: "Be the change that you wish to see in the world.", ko: "세상에서 보고 싶은 변화가 있다면 당신이 그 변화가 되어라." },
    
// 추가 명언 (성공 & 동기부여)
    { en: "Action is the foundational key to all success.", ko: "행동은 모든 성공의 가장 기초적인 핵심이다." },
    { en: "Don't watch the clock; do what it does. Keep going.", ko: "시계를 보지 말고, 시계처럼 계속 움직여라." },
    { en: "Success is not final, failure is not fatal: it is the courage to continue that counts.", ko: "성공은 끝이 아니며, 실패는 치명적이지 않다. 중요한 것은 계속하는 용기다." },
    { en: "It always seems impossible until it's done.", ko: "끝나기 전까지는 언제나 불가능해 보인다." },
    { en: "Dream big and dare to fail.", ko: "크게 꿈꾸고 과감하게 실패하라." },
    { en: "What we think, we become.", ko: "우리가 생각하는 대로 우리는 실현된다." },
    { en: "Opportunities don't happen, you create them.", ko: "기회는 일어나는 것이 아니라, 당신이 만드는 것이다." },
    { en: "Don't be afraid to give up the good to go for the great.", ko: "더 좋은 것을 위해 좋은 것을 포기하는 것을 두려워하지 마라." },
    { en: "I find that the harder I work, the more luck I seem to have.", ko: "더 열심히 일할수록, 더 많은 운이 따르는 것 같다." },
    { en: "Success usually comes to those who are too busy to be looking for it.", ko: "성공은 주로 성공을 찾느라 바쁜 사람들에게 찾아온다." },

    // 추가 명언 (지혜 & 인생)
    { en: "In the middle of difficulty lies opportunity.", ko: "어려움 속에 기회가 있다." },
    { en: "He who has a why to live can bear almost any how.", ko: "살아야 할 이유가 있는 사람은 어떤 방식의 삶도 견뎌낼 수 있다." },
    { en: "The unexamined life is not worth living.", ko: "성찰하지 않는 삶은 살 가치가 없다." },
    { en: "Everything has beauty, but not everyone sees it.", ko: "모든 것에는 아름다움이 있지만, 누구나 그것을 보는 것은 아니다." },
    { en: "It does not matter how slowly you go as long as you do not stop.", ko: "멈추지 않는다면 얼마나 천천히 가는지는 중요하지 않다." },
    { en: "Knowing yourself is the beginning of all wisdom.", ko: "너 자신을 아는 것이 모든 지혜의 시작이다." },
    { en: "A goal without a plan is just a wish.", ko: "계획 없는 목표는 단지 소망일 뿐이다." },
    { en: "Life is really simple, but we insist on making it complicated.", ko: "인생은 정말 단순하지만, 우리는 그것을 복잡하게 만들려고 애쓴다." },
    { en: "Change the world by being yourself.", ko: "너 자신이 됨으로써 세상을 변화시켜라." },
    { en: "Simplicity is the ultimate sophistication.", ko: "단순함은 궁극의 정교함이다." },

    // 추가 명언 (사랑 & 행복)
    { en: "The best thing to hold onto in life is each other.", ko: "인생에서 붙들어야 할 가장 좋은 것은 서로이다." },
    { en: "Love is composed of a single soul inhabiting two bodies.", ko: "사랑은 두 몸에 깃든 하나의 영혼으로 이루어져 있다." },
    { en: "Where there is love there is life.", ko: "사랑이 있는 곳에 삶이 있다." },
    { en: "Try to be a rainbow in someone's cloud.", ko: "누군가의 구름 낀 하늘에 무지개가 되어주라." },
    { en: "The most wasted of all days is one without laughter.", ko: "가장 헛되이 보낸 하루는 웃지 않은 하루다." },
    { en: "Happiness is not something ready made. It comes from your own actions.", ko: "행복은 이미 만들어져 있는 것이 아니다. 그것은 당신의 행동에서 온다." },
    { en: "Count your age by friends, not years.", ko: "나이를 먹은 횟수가 아니라 친구의 수로 나이를 세어라." },
    { en: "Let your smile change the world, but don't let the world change your smile.", ko: "당신의 미소로 세상을 바꾸되, 세상이 당신의 미소를 바꾸게 하지 마라." },
    { en: "Life is short, and it is up to you to make it sweet.", ko: "인생은 짧다. 그것을 달콤하게 만드는 것은 당신에게 달려있다." },
    { en: "To live is the rarest thing in the world. Most people exist, that is all.", ko: "산다는 것은 세상에서 가장 드문 일이다. 대부분의 사람은 그저 존재할 뿐이다." },

    // 추가 명언 (용기 & 도전)
    { en: "Tough times never last, but tough people do.", ko: "힘든 시간은 영원하지 않지만, 강인한 사람은 영원하다." },
    { en: "You miss 100% of the shots you don't take.", ko: "시도하지 않은 슛은 100% 빗나간다." },
    { en: "Whether you think you can or you think you can't, you're right.", ko: "할 수 있다고 생각하든 할 수 없다고 생각하든, 당신이 옳다." },
    { en: "I have not failed. I've just found 10,000 ways that won't work.", ko: "나는 실패한 것이 아니다. 단지 작동하지 않는 만 가지 방법을 발견했을 뿐이다." },
    { en: "If you're going through hell, keep going.", ko: "만약 지옥을 통과하고 있다면, 멈추지 말고 계속 가라." },
    { en: "Limit your 'always' and your 'nevers'.", ko: "'항상'과 '절대'라는 말을 제한하라." },
    { en: "Do one thing every day that scares you.", ko: "매일 당신을 두렵게 하는 일을 하나씩 하라." },
    { en: "The only way to do great work is to love what you do.", ko: "위대한 일을 하는 유일한 방법은 당신이 하는 일을 사랑하는 것이다." },
    { en: "It is never too late to be what you might have been.", ko: "당신이 되었을지도 모르는 존재가 되기에 결코 늦지 않았다." },
    { en: "Pain is temporary. Quitting lasts forever.", ko: "고통은 일시적이지만, 포기는 영원하다." },

    // 추가 명언 (짧고 강렬한 문구)
    { en: "No pain, no gain.", ko: "고통 없이는 얻는 것도 없다." },
    { en: "Stay hungry, stay foolish.", ko: "항상 갈망하라, 우직하게 나아가라." },
    { en: "Just do it.", ko: "그냥 해라." },
    { en: "Time is money.", ko: "시간은 금이다." },
    { en: "Knowledge is power.", ko: "아는 것이 힘이다." },
    { en: "Carpe Diem.", ko: "현재를 즐겨라." },
    { en: "Silence is gold.", ko: "침묵은 금이다." },
    { en: "Less is more.", ko: "적은 것이 많은 것이다." },
    { en: "Live well, love much, laugh often.", ko: "잘 살고, 많이 사랑하고, 자주 웃어라." },
    { en: "Be yourself.", ko: "너 자신이 되어라." },

    // 추가 명언 (학습 & 성장)
    { en: "Live as if you were to die tomorrow. Learn as if you were to live forever.", ko: "내일 죽을 것처럼 살고, 영원히 살 것처럼 배우라." },
    { en: "A rolling stone gathers no moss.", ko: "구르는 돌에는 이끼가 끼지 않는다." },
    { en: "Mistakes are proof that you are trying.", ko: "실수는 당신이 노력하고 있다는 증거다." },
    { en: "Learning never exhausts the mind.", ko: "배움은 결코 마음을 지치게 하지 않는다." },
    { en: "The expert in anything was once a beginner.", ko: "모든 분야의 전문가는 한때 초보자였다." },
    { en: "Don't let yesterday take up too much of today.", ko: "어제가 오늘의 너무 많은 부분을 차지하게 하지 마라." },
    { en: "You learn more from failure than from success.", ko: "성공보다 실패에서 더 많은 것을 배운다." },
    { en: "If you are not willing to learn, no one can help you.", ko: "배우려 하지 않는다면 아무도 당신을 도울 수 없다." },
    { en: "Experience is a hard teacher because she gives the test first, the lesson afterwards.", ko: "경험은 엄한 스승이다. 시험을 먼저 치르게 하고 교훈을 나중에 주기 때문이다." },
    { en: "Your attitude, not your aptitude, will determine your altitude.", ko: "당신의 재능이 아니라 태도가 당신의 높이를 결정할 것이다." },

    // 추가 명언 (희망 & 긍정)
    { en: "Keep your face always toward the sunshine—and shadows will fall behind you.", ko: "얼굴을 항상 태양 쪽으로 향하라. 그러면 그림자는 당신 뒤로 떨어질 것이다." },
    { en: "There is nothing impossible to him who will try.", ko: "시도하는 자에게 불가능이란 없다." },
    { en: "Believe in yourself.", ko: "자신을 믿어라." },
    { en: "Every moment is a fresh beginning.", ko: "모든 순간은 새로운 시작이다." },
    { en: "Hope is a waking dream.", ko: "희망은 깨어있는 꿈이다." },
    { en: "The best is yet to be.", ko: "최고의 순간은 아직 오지 않았다." },
    { en: "Look for the silver lining.", ko: "구름 뒤의 밝은 빛을 찾아라." },
    { en: "Positive anything is better than negative nothing.", ko: "긍정적인 어떤 것이 부정적인 무(無)보다 낫다." },
    { en: "Start where you are. Use what you have. Do what you can.", ko: "지금 있는 곳에서 시작하라. 가진 것을 사용하라. 할 수 있는 것을 하라." },
    { en: "Tomorrow is another day.", ko: "내일은 내일의 태양이 뜬다." },

    // 추가 명언 (인내 & 노력)
    { en: "Patience is bitter, but its fruit is sweet.", ko: "인내는 쓰지만 그 열매는 달다." },
    { en: "Genius is one percent inspiration and ninety-nine percent perspiration.", ko: "천재는 1%의 영감과 99%의 땀으로 이루어진다." },
    { en: "Don't stop when you're tired. Stop when you're done.", ko: "힘들 때 멈추지 마라. 끝났을 때 멈춰라." },
    { en: "Great things take time.", ko: "위대한 일에는 시간이 걸린다." },
    { en: "Rivers know this: there is no hurry. We shall get there some day.", ko: "강물은 알고 있다. 서두를 필요 없다는 것을. 언젠가는 다다를 것이다." },
    { en: "Slow and steady wins the race.", ko: "천천히 그리고 꾸준히 하는 자가 이긴다." },
    { en: "Energy and persistence conquer all things.", ko: "에너지와 끈기는 모든 것을 정복한다." },
    { en: "Without hustle, talent will only carry you so far.", ko: "노력 없이는 재능만으로 멀리 갈 수 없다." },
    { en: "Hard work beats talent when talent doesn't work hard.", ko: "재능이 노력하지 않을 때, 노력이 재능을 이긴다." },
    { en: "Practice makes perfect.", ko: "연습이 완벽을 만든다." },

    // 추가 명언 (친구 & 관계)
    { en: "A friend is someone who knows all about you and still loves you.", ko: "친구란 당신에 대해 모든 것을 알고도 당신을 사랑해 주는 사람이다." },
    { en: "Friendship is the only cement that will ever hold the world together.", ko: "우정은 세상을 하나로 묶어줄 유일한 시멘트다." },
    { en: "To the world you may be one person, but to one person you may be the world.", ko: "세상에게 당신은 한 사람일 뿐일지 모르지만, 한 사람에게 당신은 세상일 수 있다." },
    { en: "True friends are never apart, maybe in distance but never in heart.", ko: "진정한 친구는 결코 떨어져 있지 않다. 거리는 멀 수 있어도 마음은 그렇지 않다." },
    { en: "Walking with a friend in the dark is better than walking alone in the light.", ko: "어둠 속을 친구와 걷는 것이 빛 속을 혼자 걷는 것보다 낫다." },
    { en: "A sweet friendship refreshes the soul.", ko: "달콤한 우정은 영혼을 맑게 한다." },
    { en: "Love all, trust a few, do wrong to none.", ko: "모두를 사랑하고, 소수를 믿으며, 누구에게도 해를 끼치지 마라." },
    { en: "Kindness is a language which the deaf can hear and the blind can see.", ko: "친절은 귀머거리도 들을 수 있고 장님도 볼 수 있는 언어다." },
    { en: "Treat others the way you want to be treated.", ko: "대접받고 싶은 대로 남을 대접하라." },
    { en: "No act of kindness, no matter how small, is ever wasted.", ko: "아무리 작은 친절이라도 결코 헛되지 않다." },
// 창의성 & 영감 (Creativity & Inspiration)
    { en: "Creativity is intelligence having fun.", ko: "창의성은 지능이 즐기는 놀이다." },
    { en: "Every artist was first an amateur.", ko: "모든 예술가는 처음에는 아마추어였다." },
    { en: "Imagination is everything. It is the preview of life's coming attractions.", ko: "상상력이 전부다. 그것은 다가올 삶의 예고편이다." },
    { en: "Do not go where the path may lead, go instead where there is no path and leave a trail.", ko: "길이 이끄는 곳으로 가지 말고, 길이 없는 곳으로 가서 흔적을 남겨라." },
    { en: "You can't use up creativity. The more you use, the more you have.", ko: "창의성은 고갈되지 않는다. 쓸수록 더 생겨난다." },
    { en: "I dream my painting and I paint my dream.", ko: "나는 내 그림을 꿈꾸고, 내 꿈을 그린다." },
    { en: "Logic will get you from A to B. Imagination will take you everywhere.", ko: "논리는 당신을 A에서 B로 데려가지만, 상상력은 당신을 어디든 데려간다." },
    { en: "Art is not what you see, but what you make others see.", ko: "예술은 당신이 보는 것이 아니라, 당신이 다른 사람에게 보여주는 것이다." },
    { en: "Everything you can imagine is real.", ko: "당신이 상상할 수 있는 모든 것은 현실이다." },
    { en: "Creativity takes courage.", ko: "창의성은 용기를 필요로 한다." },

    // 리더십 & 비즈니스 (Leadership & Business)
    { en: "Leadership is action, not position.", ko: "리더십은 직위가 아니라 행동이다." },
    { en: "The way to get started is to quit talking and begin doing.", ko: "시작하는 방법은 말을 멈추고 행동하는 것이다." },
    { en: "Hire character. Train skill.", ko: "인성을 보고 채용하라. 기술은 가르치면 된다." },
    { en: "Innovation distinguishes between a leader and a follower.", ko: "혁신은 리더와 추종자를 구분 짓는다." },
    { en: "Quality is not an act, it is a habit.", ko: "품질은 행동이 아니라 습관이다." },
    { en: "Done is better than perfect.", ko: "완수가 완벽보다 낫다." },
    { en: "Business opportunities are like buses, there's always another one coming.", ko: "사업 기회는 버스와 같다. 항상 다음 차가 온다." },
    { en: "It takes 20 years to build a reputation and five minutes to ruin it.", ko: "평판을 쌓는 데는 20년이 걸리지만 무너지는 데는 5분이 걸린다." },
    { en: "Risk comes from not knowing what you're doing.", ko: "위험은 자신이 무엇을 하는지 모르는 데서 온다." },
    { en: "Success seems to be connected with action. Successful people keep moving.", ko: "성공은 행동과 연결되어 있다. 성공한 사람들은 계속해서 움직인다." },

    // 짧고 강렬한 단어 (Short & Punchy for LED)
    { en: "Dream higher.", ko: "더 높이 꿈꿔라." },
    { en: "Focus on you.", ko: "너 자신에게 집중하라." },
    { en: "Be kind.", ko: "친절하라." },
    { en: "Love yourself.", ko: "자신을 사랑하라." },
    { en: "Never settle.", ko: "현실에 안주하지 마라." },
    { en: "Keep moving.", ko: "계속 움직여라." },
    { en: "Stay humble.", ko: "겸손하라." },
    { en: "Work hard.", ko: "열심히 일하라." },
    { en: "Think different.", ko: "다르게 생각하라." },
    { en: "Be brave.", ko: "용감해져라." },

    // 긍정 & 마인드셋 (Positivity & Mindset)
    { en: "A positive mindset brings positive things.", ko: "긍정적인 마음가짐이 긍정적인 일들을 불러온다." },
    { en: "Every day may not be good, but there is something good in every day.", ko: "매일이 좋을 수는 없지만, 매일 좋은 일은 있다." },
    { en: "Be the energy you want to attract.", ko: "당신이 끌어당기고 싶은 그 에너지가 되어라." },
    { en: "Your vibe attracts your tribe.", ko: "당신의 분위기가 당신의 사람들을 끌어당긴다." },
    { en: "Happiness is an inside job.", ko: "행복은 내면에서 비롯된다." },
    { en: "Stars can't shine without darkness.", ko: "어둠 없이는 별이 빛날 수 없다." },
    { en: "Don't ruin a good today by thinking about a bad yesterday.", ko: "나쁜 어제를 생각하느라 좋은 오늘을 망치지 마라." },
    { en: "Life is 10% what happens to us and 90% how we react to it.", ko: "인생은 일어나는 일이 10%, 그에 대한 반응이 90%다." },
    { en: "Positive mind. Positive vibes. Positive life.", ko: "긍정적인 생각. 긍정적인 기운. 긍정적인 삶." },
    { en: "You are enough just as you are.", ko: "당신은 있는 그대로 충분하다." },

    // 자연 & 우주 (Nature & Universe)
    { en: "Look deep into nature, and then you will understand everything better.", ko: "자연을 깊이 들여다보라. 그러면 모든 것을 더 잘 이해하게 될 것이다." },
    { en: "The earth has music for those who listen.", ko: "지구는 듣는 이들에게 음악을 들려준다." },
    { en: "Adopt the pace of nature: her secret is patience.", ko: "자연의 속도를 따르라. 그 비밀은 인내다." },
    { en: "Colors are the smiles of nature.", ko: "색깔은 자연의 미소다." },
    { en: "Nature does not hurry, yet everything is accomplished.", ko: "자연은 서두르지 않지만, 모든 것을 이룬다." },
    { en: "The sky is not the limit. Your mind is.", ko: "하늘이 한계가 아니다. 당신의 마음이 한계다." },
    { en: "Keep your eyes on the stars, and your feet on the ground.", ko: "눈은 별을 향하고, 발은 땅을 딛고 있어라." },
    { en: "We are all made of stardust.", ko: "우리는 모두 별의 먼지로 이루어져 있다." },
    { en: "In every walk with nature one receives far more than he seeks.", ko: "자연과 함께 걸을 때 우리는 찾는 것보다 훨씬 더 많은 것을 얻는다." },
    { en: "Spring is nature's way of saying, 'Let's party!'", ko: "봄은 '파티하자!'라고 말하는 자연의 방식이다." },

    // 노력 & 끈기 (Grit & Persistence)
    { en: "Fall seven times, stand up eight.", ko: "일곱 번 넘어지면 여덟 번 일어나라." },
    { en: "Don't stop until you're proud.", ko: "자랑스러울 때까지 멈추지 마라." },
    { en: "Sweat is magic. Cover yourself in it daily to grant your wishes.", ko: "땀은 마법이다. 소원을 이루기 위해 매일 땀으로 몸을 적셔라." },
    { en: "Discipline is doing what needs to be done, even if you don't want to do it.", ko: "규율이란 하기 싫더라도 해야 할 일을 하는 것이다." },
    { en: "The only bad workout is the one that didn't happen.", ko: "유일하게 나쁜 운동은 하지 않은 운동이다." },
    { en: "A river cuts through rock, not because of its power, but because of its persistence.", ko: "강물이 바위를 뚫는 것은 힘이 아니라 끈기 때문이다." },
    { en: "It’s hard to beat a person who never gives up.", ko: "포기하지 않는 사람은 이기기 어렵다." },
    { en: "Go the extra mile. It's never crowded there.", ko: "한 걸음 더 나아가라. 그곳은 결코 붐비지 않는다." },
    { en: "Determination is power.", ko: "결단력이 힘이다." },
    { en: "Consistency is key.", ko: "일관성이 열쇠다." },

    // 사랑 & 우정 2 (Love & Relationship)
    { en: "Love is the only gold.", ko: "사랑만이 유일한 금이다." },
    { en: "To love and be loved is to feel the sun from both sides.", ko: "사랑하고 사랑받는 것은 태양을 양쪽에서 느끼는 것과 같다." },
    { en: "We accept the love we think we deserve.", ko: "우리는 우리가 받을 자격이 있다고 생각하는 만큼의 사랑을 받아들인다." },
    { en: "Love is friendship that has caught fire.", ko: "사랑은 불이 붙은 우정이다." },
    { en: "A friend to all is a friend to none.", ko: "모두의 친구는 누구의 친구도 아니다." },
    { en: "Love is being stupid together.", ko: "사랑은 함께 바보가 되는 것이다." },
    { en: "The best healing therapy is friendship and love.", ko: "최고의 치유법은 우정과 사랑이다." },
    { en: "Hold my hand and I'll go anywhere with you.", ko: "내 손을 잡아, 너와 함께라면 어디든 갈게." },
    { en: "Distance means so little when someone means so much.", ko: "누군가가 소중하다면 거리는 아무것도 아니다." },
    { en: "Life is the flower for which love is the honey.", ko: "인생은 꽃이고 사랑은 그 꽃의 꿀이다." },

    // 철학 & 사색 (Philosophy & Thought)
    { en: "I think, therefore I am.", ko: "나는 생각한다, 고로 존재한다." },
    { en: "To be is to do.", ko: "존재하는 것은 행동하는 것이다." },
    { en: "Knowledge speaks, but wisdom listens.", ko: "지식은 말하지만 지혜는 듣는다." },
    { en: "The only true wisdom is in knowing you know nothing.", ko: "유일한 참된 지혜는 당신이 아무것도 모른다는 것을 아는 것이다." },
    { en: "Life must be lived forwards, but can only be understood backwards.", ko: "삶은 앞으로 살아가야 하지만, 이해는 뒤돌아볼 때만 가능하다." },
    { en: "We are what we repeatedly do.", ko: "우리가 반복적으로 하는 행동이 바로 우리 자신이다." },
    { en: "Happiness is the highest good.", ko: "행복은 최고의 선이다." },
    { en: "Man is the measure of all things.", ko: "인간은 만물의 척도다." },
    { en: "He who has overcome his fears will truly be free.", ko: "두려움을 극복한 자만이 진정으로 자유로워질 것이다." },
    { en: "Beware the barrenness of a busy life.", ko: "바쁜 삶의 공허함을 경계하라." },

    // 미래 & 비전 (Future & Vision)
    { en: "The future belongs to those who believe in the beauty of their dreams.", ko: "미래는 꿈의 아름다움을 믿는 자들의 것이다." },
    { en: "Create the highest, grandest vision possible for your life.", ko: "당신의 삶을 위해 가능한 가장 높고 장대한 비전을 세워라." },
    { en: "Your time is limited, so don't waste it living someone else's life.", ko: "당신의 시간은 제한적이다. 남의 인생을 사느라 낭비하지 마라." },
    { en: "Don't wait for opportunity. Create it.", ko: "기회를 기다리지 마라. 기회를 만들어라." },
    { en: "The best preparation for tomorrow is doing your best today.", ko: "내일을 위한 최선의 준비는 오늘 최선을 다하는 것이다." },
    { en: "Change is the law of life.", ko: "변화는 삶의 법칙이다." },
    { en: "Act as if what you do makes a difference. It does.", ko: "당신의 행동이 변화를 만드는 것처럼 행동하라. 실제로 그렇다." },
    { en: "Go confidently in the direction of your dreams.", ko: "당신의 꿈을 향해 자신 있게 나아가라." },
    { en: "You define your own life. Don't let other people write your script.", ko: "당신의 인생은 당신이 정의한다. 다른 사람이 당신의 대본을 쓰게 하지 마라." },
    { en: "Believe you can and you're halfway there.", ko: "할 수 있다고 믿으면 절반은 온 것이다." },

    // 짧은 격언 (Short Maxims)
    { en: "No guts, no glory.", ko: "배짱이 없으면 영광도 없다." },
    { en: "Winners never quit.", ko: "승자는 결코 포기하지 않는다." },
    { en: "Lead by example.", ko: "솔선수범하라." },
    { en: "Trust the process.", ko: "과정을 믿어라." },
    { en: "Focus on the good.", ko: "좋은 것에 집중하라." },
    { en: "Choose joy.", ko: "기쁨을 선택하라." },
    { en: "Stay strong.", ko: "강해져라." },
    { en: "Dream on.", ko: "계속 꿈꾸라." },
    { en: "Be a warrior.", ko: "전사가 되어라." },
    { en: "Shine bright.", ko: "밝게 빛나라." }
];

